build: false
clone_depth: 1
platform: x86

branches:
  except:
    - /wip.*/

environment:
    matrix:
        - PHP_DOWNLOAD_FILE: php-7.0.16-nts-Win32-VC14-x86.zip

cache:
    - c:\php -> .appveyor.yml
    - '%LOCALAPPDATA%\Composer'

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)
    - git config --global core.autocrlf input

install:
    - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
    - cd c:\php
    - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/%PHP_DOWNLOAD_FILE%
    - IF %PHP%==1 7z x %PHP_DOWNLOAD_FILE% -y > 7z.log
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - copy php.ini-production php.ini /Y
    - echo date.timezone="UTC" >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_fileinfo.dll >> php.ini
    - cd %APPVEYOR_BUILD_FOLDER%
    - composer update --no-progress --ansi

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - composer test
