language: php

git:
  depth: 2

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 7.1
    - php: 7.0
      env:
      - LINT=true
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  # Verify application version and Git tag match on tagged builds
  - if [[ ! -z "$TRAVIS_TAG" ]]; then
      composer application-version-guard;
    fi
  - if [[ $LINT = true ]]; then
      composer cs-lint;
    fi
  - composer test
